---
- name: Setup new user
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Create a new user
      ansible.builtin.user:
        name: "ansible"
        state: present
        groups: sudo
        append: true
        password: "{{ password | password_hash('sha512') }}"
    - name: "Create .ssh directory"
      ansible.builtin.file:
        path: "/home/ansible/.ssh"
        state: "directory"
        owner: "ansible"
        group: ansible
        mode: "700"