---
 
- name: Install Apache and PHP
  hosts: all
  become: true
  tasks:
 
  - name: Install Apache and PHP
    package:
      name:
        - "Template:Apache package"
        - "Template:Php package"
      state: present
      update_cache: yes