---

- hosts: All
  become: True
  tasks:

  - name: Update repository index
    apt:
      update_cache: true

  - name: Upgrade distibution
    ansible.builtin.apt:
      upgrade: dist

  - name: Install apache2
    apt:
      name: apache2
      state: absent

  - name: Add php support for apache
    apt:
      name: libapache2-mod-php
      state: absent
