---

- hosts: all
  become: true
  pre_tasks:


  - name: install updates
    tags: always 
    apt:
      upgrade: dist
      update_cache: true
    

- hosts: test_servers
  become: true
  tasks:

  - name: install apache2 package
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest

  - name: copy html file for site
    tags: apache,apache,apache2,httpd
    copy:
       src: default_site.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644    

  - name: install mariadb package (Debian)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
      