---

- hosts: test_servers
  become: true
  pre_tasks:


  - name: install updates
    tags: always 
    apt:
      upgrade: dist
      update_cache: true
    

- hosts: test_servers
  become: true
  tasks:

  - name: install apache2 package
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest

  - name: copy html file for site
    tags: apache,apache,apache2,httpd
    copy:
       src: default_site.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644    

- hosts: test_servers
  become: true
  tasks:

  - name: install unzip
    ansible.builtin.package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_arm64.zip
      dest: /usr/local/bin
      remote_src: true
      mode: 0755
      owner: root
      group: root   
 


  - name: install mariadb package (Debian)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest


  

