---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Debian)
    apt:
      upgrade: dist
      update_cache: true
    when: ansible_distribution == ["Ubuntu", "Debian"]

  - name: install tmux
    apt:
      name: tmux
      state: absent
    #  state: true
    when: ansible_distribution == ["Ubuntu", "Debian"]
