---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates 
    apt:
      upgrade: dist
      update_cache: true

   
  - name: install cockpit
    apt:
      name: cockpit
      
    
  