---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Debian)
    apt:
      upgrade: dist
      update_cache: true
    when: ansible_distribution == "Debian"


  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: true
    when: ansible_distribution == "Ubuntu"

  - name: install tmux
    apt:
      name: tmux
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install tmux
    apt:
      name: tmux
      state: latest
    when: ansible_distribution == "CentOS"  